In [1]:
import pandas as pd
import json

In [2]:
#Convert PDF to Images , each page converted into seprate image

from pdf2image import convert_from_path

from pdf2image.exceptions import (
 PDFInfoNotInstalledError,
 PDFPageCountError,
 PDFSyntaxError
)

In [3]:
# Function to convert to Strings  
def listToString(s):  
    
    # initialize an empty string 
    str1 = ""  
    
    # traverse in the string   
    for ele in s:  
        str1 += ele   
    
    # return string   
    return str1

In [4]:
#function to find all floats values from list
def solve(lis):
    for x in lis:
        try:
            float(x)
            return True
        except:
            return False

In [5]:
# OCR Works Here

try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

def ocr_core(filename):
  
    text = pytesseract.pytesseract.image_to_string(Image.open(filename))
    return text  # Then we will print the text in the image

In [56]:
# Main Functions for OCR
images = convert_from_path('a6.pdf')
img=[]
texts = []
for i, image in enumerate(images):
    fname = "image" + str(i) + ".png"
    img.append(fname)
    
    image.save(fname, "PNG")
    text  =  ocr_core(fname)
    
    text = listToString(text)  
    texts.append(text)
    text1 = listToString(texts)

In [57]:
print(text1)

PROCESSED AT: grmontsng Hemoglobin Aye Testing
Thyrocare @JNGsP
D-37/1,TTC MIDC,Turbhe, J

Navi Mumbai-400 703 SESE



abby Thyrocare’

COLLEGE of AMERICAN PATHOLOGISTS



Think Thyroid. Think Thyrocare.

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com (www.thyrocare.com



NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT

. (5311169953),PRABHU CLINICAL
REF. BY + SELF LABORATORY,DR.YEKKALA RAMAKRISHNA
TEST ASKED : HBA,HEMOGRAM - 6 PART (DIFF) HOSPITAL RAMARAOPETA NARSIPATNAM

531116,531116























TEST NAME TECHNOLOGY VALUE UNITS
HbAi1c - (HPLC - NGSP Certified)
H.P.L.C 8.3 %
Reference Range :
Reference Range: As per ADA Guidelines Guidance For Known Diabetics
Below 5.7% : Normal Below 6.5% : Good Control
5.7% - 6.4% : Prediabetic 6.5% - 7% : Fair Control
>=6.5% : Diabetic 7.0% - 8% : Unsatisfactory Control
>8% : Poor Control
Method : Fully Automated H.P.L.C. using Biorad Variant II Turbo, NGSP Certified.
AVERAGE BLOOD GLUCOSE (ABG) CALCULATED 192 mg/dl
Reference Range :
90 - 120 mg/dl : Good Control
121 - 150 mg/dl : Fair Control
151 - 180 mg/dl : Unsatisfactory Control
> 180 mg/dl : Poor Control
Method : Derived from HBA1c_ values
Please correlate with clinical conditions.
Sample Collected on (SCT) :26 Aug 2019 18:00
Sample Received on (SRT) 27 Aug 2019 22:50 Goole?
Report Released on (RRT) :28 Aug 2019 08:25 Oe <a

Sample Type bres. #EDTA Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)
Labcode : 2708040370/A6750

Re . Page : 1 of 9
Barcode Ou :M9261080
PROCESSED AT:
Thyrocare

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703

CAP
ACCREDITED

COLLEGE of AMERICAN PATHOLOGISTS



Thyrocare’

Think Thyroid. Think Thyrocare.



centiieAte no: C2407

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com (www.thyrocare.com





NAME MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT :

REF. BY + SELF (5311169953),PRABHU CLINICAL
LABORATORY,DR.YEKKALA RAMAKRISHNA

TEST ASKED HBA,HEMOGRAM - 6 PART (DIFF) HOSPITAL RAMARAOPETA NARSIPATNAM
531116,531116

TEST NAME VALUE UNITS REFERENCE RANGE

TOTAL LEUCOCYTES COUNT 6.4 X103/pL  4.0-10.0

NEUTROPHILS 49.7 % 40-80

LYMPHOCYTE PERCENTAGE 42.8 % 20-40

MONOCYTES 2.3 % 0-10

EOSINOPHILS 4.7 % 0.0-6.0

BASOPHILS 0.2 % <2

IMMATURE GRANULOCYTE PERCENTAGE(IG%) 0.3 % 0-0.5

NEUTROPHILS - ABSOLUTE COUNT 3.18 X103/uL  2.0-7.0

LYMPHOCYTES - ABSOLUTE COUNT 2.74 X103/pL  1.0-3.0

MONOCYTES - ABSOLUTE COUNT 0.15 X 103 / pL 0.2-1

BASOPHILS - ABSOLUTE COUNT 0.01 X103/pL  0-0.1

EOSINOPHILS - ABSOLUTE COUNT 0.3 X103/pL  0-0.5

IMMATURE GRANULOCYTES(IG) 0.02 X103/pL  0-0.3

TOTAL RBC 6.13 X1046/pL 4.5-5.5

NUCLEATED RED BLOOD CELLS Nil X103/uL  <0.01

NUCLEATED RED BLOOD CELLS % Nil % <0.01

HEMOGLOBIN 18.1 g/dL 13-17

HEMATOCRIT(PCV) 50.68 % 40-50

MEAN CORPUSCULAR VOLUME(MCV) 100.2 fl 83-101

MEAN CORPUSCULAR HEMOGLOBIN(MCH) 29.5 pq 27-32

MEAN CORP.HEMO.CONC(MCHC) 29.5 g/dL 31.5-34.5

RED CELL DISTRIBUTION WIDTH - SD(RDW-SD) 62.9 fL 39-46

RED CELL DISTRIBUTION WIDTH (RDW-CV) 17.6 % 11.6-14

PLATELET DISTRIBUTION WIDTH(PDW) 11.1 fL 9.6-15.2

MEAN PLATELET VOLUME(MPV) 9.4 fL 6.5-12

PLATELET COUNT 222 X103/uL 150-400

PLATELET TO LARGE CELL RATIO(PLCR) 20.5 % 19.7-42.4

PLATELETCRIT(PCT) 0.21 % 0.19-0.39

Remarks: ALERT !!! Anisocytosis

Please Correlate with clinical conditions.

Method : Fully automated bidirectional analyser (6 Part Differential SYSMEX XN-1000)

(This device performs hematology analyses according to the Hydrodynamic Focussing (DC method), Flow
Cytometry Method (using a semiconductor laser), and SLS- hemoglobin method)



Sample Collected on (SCT)
Sample Received on (SRT)
Report Released on (RRT)
Sample Type

Labcode

Barcode

:26 Aug 2019 18:00
227 Aug 2019 22:50
:28 Aug 2019 08:25
: EDTA

: 2708040370/A6750
: M9261080

ln!

ra

Dr.Prachi Sinkar MD(Path)

Dr.Caesar Sengupta MD(Micro)
Page : 2 of 9
PROCESSED AT:

Thyrocare wi CAP orl Thyro Cc are’

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703 Think Thyroid. Think Thyrocare.



Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com (www.thyrocare.com



REPORT
NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT

. (5311169953),PRABHU CLINICAL

REF. BY + SELF LABORATORY,DR.YEKKALA RAMAKRISHNA
TEST ASKED : AAROGYAM B HOSPITAL RAMARAOPETA NARSIPATNAM
531116,531116

TEST NAME TECHNOLOGY VALUE UNITS

IRON PHOTOMETRY 69.1 g/dl
Reference Range :

Male : 65-175

Female : 50 - 170

Method : _ FERROZINE METHOD WITHOUT DEPROTEINIZATION

TOTAL IRON BINDING CAPACITY (TIBC) PHOTOMETRY 348 g/dl
Reference Range :

Male: 225 - 535 ug/dl Female: 215 - 535 ug/dl

Method : _SPECTROPHOTOMETRIC ASSAY

% TRANSFERRIN SATURATION CALCULATED 19.86 %
Reference Range :

13-45

Method : DERIVED FROM IRON AND TIBC VALUES

Please correlate with clinical conditions.



Sample Collected on (SCT) :26 Aug 2019 18:00

Sample Received on (SRT) 127 Aug 2019 22:53 Goole?

Report Released on (RRT) :28 Aug 2019 02:10 Oe <a

Sample Type #SERUM Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)
Labcode 1 2708040550/A6750

Page : 3 of 9
Barcode =N7212022
PROCESSED AT:
Thyrocare

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703



ecap,, Thyrocare’

COLLEGE of AMERICAN PATHOLOGISTS



Think Thyroid. Think Thyrocare.

CERTIFICATE NO.: NC=2007

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com www.thyrocare.com





NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT :
REF. BY : SELF (5311169953), PRABHU CLINICAL

LABORATORY, DR.YEKKALA RAMAKRISHNA HOSPITAL
TEST ASKED  AAROGYAM B RAMARAOPETA NARSIPATNAM 531116,531116
TEST NAME TECHNOLOGY VALUE UNITS NORMAL RANGE
ALKALINE PHOSPHATASE PHOTOMETRY 64.5 U/L 45 - 129
BILIRUBIN - TOTAL PHOTOMETRY 0.35 mg/dl 0.3-1.2
BILIRUBIN -DIRECT PHOTOMETRY 0.08 mg/dl < 0.3
BILIRUBIN (INDIRECT) CALCULATED 0.27 mg/dl 0-0.9
GAMMA GLUTAMYL TRANSFERASE (GGT) PHOTOMETRY 91.1 u/I <55
ASPARTATE AMINOTRANSFERASE (SGOT ) PHOTOMETRY 22.5 u/| <35
ALANINE TRANSAMINASE (SGPT) PHOTOMETRY 21.4 u/| < 45
PROTEIN - TOTAL PHOTOMETRY 6.6 gm/dl 5.7-8.2
ALBUMIN - SERUM PHOTOMETRY 41 gm/dl 3.2-4.8
SERUM ALB/GLOBULIN RATIO CALCULATED 1.64 Ratio 0.9-2
SERUM GLOBULIN PHOTOMETRY 2.5 gm/dL 2.5-3.4

Please correlate with clinical conditions.

Method :

ALKP - MODIFIED IFCC METHOD

BILT - VANADATE OXIDATION

BILD - VANADATE OXIDATION

BILI - DERIVED FROM SERUM TOTAL AND DIRECT BILIRUBIN VALUES
GGT - MODIFIED IFCC METHOD

SGOT - IFCC* WITHOUT PYRIDOXAL PHOSPHATE ACTIVATION
SGPT - IFCC* WITHOUT PYRIDOXAL PHOSPHATE ACTIVATION
PROT - BIURET METHOD

SALB - ALBUMIN BCG:METHOD (COLORIMETRIC ASSAY ENDPOINT)
A/GR - DERIVED FROM SERUM ALBUMIN AND PROTEIN VALUES
SEGB - DERIVED FROM SERUM ALBUMIN AND PROTEIN VALUES

Sample Collected on (SCT) : 26 Aug 2019 18:00

Sample Received on (SRT) : 27 Aug 2019 22:53 heen’

Report Released on (RRT) : 28 Aug 2019 02:10 q OL “

Sample Type : SERUM .

Labcode : 2708040550/A6750 Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)

Barcode : N7212022 Page : 4 of 9
PROCESSED AT:
Thyrocare

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703



ecap,, Thyrocare’

COLLEGE of AMERICAN PATHOLOGISTS

canmwoheno. WOsor Think Thyroid. Think Thyrocare.



Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com www.thyrocare.com



NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT :
REF. BY : SELF (5311169953),PRABHU CLINICAL
LABORATORY,DR.YEKKALA RAMAKRISHNA HOSPITAL



TEST ASKED  AAROGYAM B RAMARAOPETA NARSIPATNAM 531116,531116

TEST NAME TECHNOLOGY VALUE UNITS NORMAL RANGE
TOTAL CHOLESTEROL PHOTOMETRY 220 mg/dl 125-200

HDL CHOLESTEROL - DIRECT PHOTOMETRY 36 mg/dl 35-80

LDL CHOLESTEROL - DIRECT PHOTOMETRY 167 mg/dl 85-130
TRIGLYCERIDES PHOTOMETRY 188 mg/dl 25-200

TC/ HDL CHOLESTEROL RATIO CALCULATED 6.1 Ratio 3-5

LDL / HDL RATIO CALCULATED 4.7 Ratio 1.5-3.5

VLDL CHOLESTEROL CALCULATED 37.6 mg/dl 5-40

NON-HDL CHOLESTEROL CALCULATED 184.1 mg/dl < 160



Please correlate with clinical conditions.

Method :

CHOL - CHOD POD METHOD

HCHO - ENZYME SELECTIVE PROTECTION METHOD

LDL - HOMOGENOUS ENZYMATIC COLORIMETRIC ASSAY

TRIG - ENZYMATIC COLORIMETRIC METHOD (GPO) [HIGHLY INFLUENCED BY LEVEL OF FASTING]
TC/H - DERIVED FROM SERUM CHOLESTEROL AND HDL VALUES

LDL/ - DERIVED FROM SERUM HDL AND LDL VALUES

VLDL - DERIVED FROM SERUM TRIGLYCERIDE VALUES

NHDL - DERIVED FROM SERUM CHOLESTEROL AND HDL VALUES

*REFERENCE RANGES AS PER NCEP ATP III GUIDELINES:

TOTAL CHOLESTEROL (mg/dl) HDL (mg/dl) LDL (mg/dl) TRIGLYCERIDES (mg/dl)

DESIRABLE <200 Low <40 OPTIMAL <100 NORMAL <150

BORDERLINE HIGH 200-239 HIGH >60 NEAR OPTIMAL 100-129 BORDERLINE HIGH 150-199

HIGH >240 BORDERLINE HIGH 130-159 HIGH 200-499
HIGH 160-189 VERY HIGH >500
VERY HIGH >190

Alert !!! 10-12 hours fasting is mandatory for lipid parameters. If not, values might fluctuate.

Sample Collected on (SCT) : 26 Aug 2019 18:00

Sample Received on (SRT) : 27 Aug 2019 22:53 heen’

Report Released on (RRT) : 28 Aug 2019 02:10 q OL “

Sample Type : SERUM .

Labcode : 2708040550/A6750 Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)

Barcode : N7212022 Page : 5 of 9
PROCESSED AT:



Thyrocare
D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703 axa eno. Oe?



ECAP, Thyrocare’

COLLEGE of AMERICAN PATHOLOGISTS

Think Thyroid. Think Thyrocare.

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com (www.thyrocare.com



REPORT



NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT

. (5311169953),PRABHU CLINICAL
REF. BY + SELF LABORATORY, DR.YEKKALA RAMAKRISHNA HOSPITAL
TEST ASKED : AAROGYAM B RAMARAOPETA NARSIPATNAM 531116,531116
TEST NAME TECHNOLOGY VALUE UNITS REFERENCE RANGE
TOTAL TRIIODOTHYRONINE (T3) CLA 99 ng/dl 60-200
TOTAL THYROXINE (T4) CLA 6.4 ug/dl 4.5-12
THYROID STIMULATING HORMONE (TSH) CLA 3.42 uIU/ml 0.3-5.5

Comments : SUGGESTING THYRONORMALCY

Please correlate with clinical conditions.

Method :

T3 - COMPETITIVE CHEMI LUMINESCENT IMMUNO ASSAY
T4 - COMPETITIVE CHEMI LUMINESCENT IMMUNO ASSAY
TSH - SANDWICH CHEMI LUMINESCENT IMMUNO ASSAY

Sample Collected on (SCT) : 26 Aug 2019 18:00
Sample Received on (SRT) : 27 Aug 2019 22:53 ac tt?
Report Released on (RRT) : 28 Aug 2019 02:10 Oe -
Sample Type : SERUM oo. .
Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)
Labcode : 2708040550/A6750
Page : 6 of 9

Barcode : N7212022
PROCESSED AT:
Thyrocare

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703



ecap,, Thyrocare’

COLLEGE of AMERICAN PATHOLOGISTS



Think Thyroid. Think Thyrocare.

CERTIFICATE NO.: NC=2007

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com www.thyrocare.com



NAME : MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT :
REF. BY : SELF (5311169953),PRABHU CLINICAL
LABORATORY,DR.YEKKALA RAMAKRISHNA HOSPITAL



TEST ASKED  AAROGYAM B RAMARAOPETA NARSIPATNAM 531116,531116

TEST NAME TECHNOLOGY VALUE UNITS NORMAL RANGE
BLOOD UREA NITROGEN (BUN) PHOTOMETRY 12.26 mg/dl 7-25
CREATININE - SERUM PHOTOMETRY 0.74 mg/dl 0.6-1.1

BUN / SR.CREATININE RATIO CALCULATED 16.57 Ratio 9:1-23:1
CALCIUM PHOTOMETRY 9.16 mg/dl 8.8-10.6

URIC ACID PHOTOMETRY 3.3 mg/dl 4.2 -7.3

Please correlate with clinical conditions.

Method :

BUN - KINETIC UV ASSAY.

SCRE - CREATININE ENZYMATIC METHOD

B/CR - DERIVED FROM SERUM BUN AND CREATININE VALUES
CALC - ARSENAZO III METHOD, END POINT.

URIC - URICASE / PEROXIDASE METHOD

Sample Collected on (SCT) : 26 Aug 2019 18:00

Sample Received on (SRT) : 27 Aug 2019 22:53 heen’

Report Released on (RRT) : 28 Aug 2019 02:10 q OL “

Sample Type : SERUM .

Labcode : 2708040550/A6750 Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)

Barcode : N7212022 Page : 7 of 9
PROCESSED AT:

Thyrocare Thyrocare’

D-37/1,TTC MIDC,Turbhe,
Navi Mumbai-400 703 Think Thyroid. Think Thyrocare.

Corporate Office : Thyrocare Technologies Limited 9 D-37/3, TTC MIDC, Turbhe, Navi Mumbai - 400703
© 022 - 3090 0000 / 41252525 8691866066 4 wellness@thyrocare.com (www.thyrocare.com



NAME = MR SRIKANTH (38Y/M) SAMPLE COLLECTED AT :
REF. BY + SELF (5311169953),PRABHU CLINICAL
‘ . LABORATORY,DR.YEKKALA RAMAKRISHNA
TEST ASKED : AAROGYAM B HOSPITAL RAMARAOPETA NARSIPATNAM
531116,531116

TEST NAME TECHNOLOGY VALUE UNITS
EST. GLOMERULAR FILTRATION RATE (eGFR) CALCULATED 117 mL/min/1.73 m2

Reference Range :-

> = 90 : Normal
60 - 89 : Mild Decrease
45-59 : Mild to Moderate Decrease

30-44 : Moderate to Severe Decrease
15-29 : Severe Decrease

Clinical Significance

The normal serum creatinine reference interval does not necessarily reflect a normal GFR for a patient. Because mild
and moderate kidney injury is poorly inferred from serum creatinine alone. Thus, it is recommended for clinical
laboratories to routinely estimate glomerular filtration rate (eGFR), a “gold standard” measurement for assessment of
renal function, and report the value when serum creatinine is measured for patients 18 and older, when appropriate
and feasible. It cannot be measured easily in clinical practice, instead, GFR is estimated from equations using serum
creatinine, age, race and sex. This provides easy to interpret information for the doctor and patient on the degree of
renal impairment since it approximately equates to the percentage of kidney function remaining. Application of
CKD-EPI equation together with the other diagnostic tools in renal medicine will further improve the detection and
management of patients with CKD.

Reference

Levey AS, Stevens LA, Schmid CH, Zhang YL, Castro AF, 3rd, Feldman HI, et al. A new equation to estimate glomerular
filtration rate. Ann Intern Med. 2009;150(9):604-12.

Please correlate with clinical conditions.

Method:- CKD-EPI Creatinine Equation

«ww End of report ~~

Sample Collected on (SCT) : 26 Aug 2019 18:00
Sample Received on (SRT) 127 Aug 2019 22:53 Goole?
Report Released on (RRT) :28 Aug 2019 02:10 “ ™

Sample Type bres: SERUM Dr.Prachi Sinkar MD(Path) Dr.Caesar Sengupta MD(Micro)
Labcode : 2708040550/A6750

Barcode RO :N7212022 Page : 8 of 9
CONDITIONS OF REPORTING

“ The reported results are for information and interpretation of the referring doctor only.

“It is presumed that the tests performed on the specimen belong to the patient; named or identified.

“Results of tests may vary from laboratory to laboratory and also in some parameters from time to time for the
same patient.

“Should the results indicate an unexpected abnormality, the same should be reconfirmed.

“Only such medical professionals who understand reporting units, reference ranges and limitations of
technologies should interpret results.

“This report is not valid for medico-legal purpose.

“Neither Thyrocare, nor its employees/representatives assume any liability, responsibility for any loss or
damage that may be incurred by any person as a result of presuming the meaning or contents of the report.

EXPLANATIONS

“Majority of the specimen processed in the laboratory are collected by Pathologists and Hospitals we call them
as "Clients".

~* Name - The name is as declared by the client and recored by the personnel who collected the specimen.

“  Ref.Dr - The name of the doctor who has recommended testing as declared by the client.

“ Labcode - This is the accession number in our laboratory and it helps us in archiving and retrieving the data.

“Barcode - This is the specimen identity number and it states that the results are for the specimen bearing
the barcode (irrespective of the name).

SCP - Specimen Collection Point - This is the location where the blood or specimen was collected as declared by
the client.

“SCT - Specimen Collection Time - The time when specimen was collected as declared by the client.

“SRT - Specimen Receiving Time - This time when the specimen reached our laboratory.

“* RRT - Report Releasing Time - The time when our pathologist has released the values for Reporting.

“ Reference Range - Means the range of values in which 95% of the normal population would fall.

SUGGESTIONS

“+ Values out of reference range requires reconfirmation before starting any medical treatment.

“* Retesting is needed if you suspect any quality shortcomings.

“* Testing or retesting should be done in accredited laboratories.

“For suggestions, complaints or feedback, write to us at info@thyrocare.com or call us on
022-3090 0000 / 4125 2525

“* SMS:<Labcode No.> to 9870666333

Preventive Healthcare is now at your fingertips!
t=)
Booking

Track your
Confirmatios Technician














Rig tT Nt





Ly

Sample
Testing

=
a &
&

explore & Select
Test / Profil







Blood
Collection









Focus TB

Towards a TB free world



“Fight TB with power of
Rapid Technology”











Focus TB, powered by Thyrocare.
A brand that will focus on TB, which is one of the major public health

problems in the country. Call : 022 - 3090 0000/4125 2525

Tuberculosis (TB) is a transmissible, airborne infection caused by info@focustb.com
Mycobacterium tuberculosis (MTB). \t transpires usually when a
person inhales microscopic droplet nuclei containing viable
bacteria, spread through coughing by persons who have
infectious TB.

Page : 9 of 9

In [58]:
# Word List for Keywords to Fetch Info
word_list = [
'H.P.L.C',
'AVERAGE BLOOD GLUCOSE (ABG)',
'TOTAL LEUCOCYTES COUNT',
'NEUTROPHILS',
'LYMPHOCYTE PERCENTAGE',
'MONOCYTES',
'EOSINOPHILS',
'BASOPHILS',
'IMMATURE GRANULOCYTE PERCENTAGE(IG%)',
'NEUTROPHILS - ABSOLUTE COUNT',
'LYMPHOCYTES - ABSOLUTE COUNT',
'MONOCYTES - ABSOLUTE COUNT',
'BASOPHILS - ABSOLUTE COUNT',
'EOSINOPHILS - ABSOLUTE COUNT',
'IMMATURE GRANULOCYTES(IG)',
'TOTAL RBC',
'NUCLEATED RED BLOOD CELLS',
'HEMOGLOBIN',
'HEMATOCRIT(PCV)',
'MEAN CORPUSCULAR VOLUME(MCV)',
'MEAN CORPUSCULAR HEMOGLOBIN(MCH)',
'MEAN CORP.HEMO.CONC(MCHC)',
'RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)',
'RED CELL DISTRIBUTION WIDTH (RDW-CV)',
'PLATELET DISTRIBUTION WIDTH(PDW)',
'MEAN PLATELET VOLUME(MPV)',
'PLATELET COUNT',
'PLATELET TO LARGE CELL RATIO(PLCR)',
'PLATELETCRIT(PCT)',
'IRON',
'TOTAL IRON BINDING CAPACITY (TIBC)',
'% TRANSFERRIN SATURATION',
'ALKALINE PHOSPHATASE',
'BILIRUBIN - TOTAL',
'BILIRUBIN -DIRECT',
'BILIRUBIN (INDIRECT)',
'GAMMA GLUTAMYL TRANSFERASE (GGT)',
'ASPARTATE AMINOTRANSFERASE (SGOT )',
'ALANINE TRANSAMINASE (SGPT)',
'PROTEIN - TOTAL',
'ALBUMIN - SERUM',
'SERUM ALB/GLOBULIN RATIO',
'SERUM GLOBULIN',
'TOTAL CHOLESTEROL',
'HDL CHOLESTEROL - DIRECT',
'LDL CHOLESTEROL - DIRECT',
'TRIGLYCERIDES',
'TC/ HDL CHOLESTEROL RATIO',
'LDL / HDL RATIO',
'VLDL CHOLESTEROL',
'NON-HDL CHOLESTEROL',
'TOTAL TRIIODOTHYRONINE (T3)',
'TOTAL THYROXINE',
'THYROID STIMULATING HORMONE',
'BLOOD UREA NITROGEN (BUN)',
'CREATININE - SERUM',
'BUN / SR.CREATININE RATIO',
'CALCIUM',
'URIC ACID',
'EST. GLOMERULAR FILTRATION RATE',
'Vitamin',
]

In [134]:
# Wordlist to Delete Useless data from the list
stopwords = ['X103pL','X103/pL','-','4.0-10.0','X103/uL','2.0-7.0','1.0-3.0','%','C.L.L.A',
             'C.LI.A','ng/d|','HIU/ml','CLA','/','Nil','.-',
            '20-40','PERCENTAGE(IG%)','0-0.5','IMMATURE', '40-80','0.0-6.0','0.0-6.0','0-0.1','mg/dl',
            '<2','0-10','<','>', 'X', '103', 'pL', '0.2-1','X1046/pL', '<0.01','g/dL', '13-17','fl', '83-101',
            'pq', '27-32','g/dL', '31.5-34.5','0-0.3','40-50','fL', '39-46','11.6-14','9.6-15.2','4.5-5.5','g/dl',
           'PHOTOMETRY','CALCULATED','(eGFR)', 'Ratio', '9:1-23:1', '(mg/dl)',
             'mL/min/1.73', 'm2','uIU/ml', '0.3-5.5','85-130','35-80','125-200','gm/dL', '2.5-3.4','u/|', '<35','(',')',
            'u/I', '<55','gm/dl', '3.2-4.8''5.7-8.2','6.5-12','19.7-42.4','0.19-0.39','0.3-1.2','0-0.9','5.7-8.2',
            '3.2-4.8','3-5', 'ng/dl', '60-200','ug/dl', '4.5-12','7-25','0.6-1.1','8.8-10.6','-7.3','5-40','U/L','1.5-3.5',
            'RATIO','150-400','4.0-10.0','25-200','B12 pg/mL 911','B12' ,'pg/mL' ,'911',]

In [135]:
# Main function to collect the data

data = []
for row in text1.split('\n'):
    for word in list(word_list):
        if row.startswith(word):
            word = row.split()
            word = word
            for word_name in list(word):  
                if word_name in stopwords:

                    word.remove(word_name)
 
            for i in word:
                if  solve(i):
                    null = i
                    word.remove(null)
                    i = float(i)
            
            word = [x for x in word if not isinstance(x, int)]   
            word = [' '.join(word)]
            print(word)
            word.append(i)
            #word.remove(str(i))
            print(word)
            data.append(word)

['H.P.L.C']
['H.P.L.C', 8.3]
['AVERAGE BLOOD GLUCOSE (ABG)']
['AVERAGE BLOOD GLUCOSE (ABG)', 192.0]
['TOTAL LEUCOCYTES COUNT']
['TOTAL LEUCOCYTES COUNT', 6.4]
['NEUTROPHILS']
['NEUTROPHILS', 49.7]
['LYMPHOCYTE PERCENTAGE']
['LYMPHOCYTE PERCENTAGE', 42.8]
['MONOCYTES']
['MONOCYTES', 2.3]
['EOSINOPHILS']
['EOSINOPHILS', 4.7]
['BASOPHILS']
['BASOPHILS', 0.2]
['GRANULOCYTE']
['GRANULOCYTE', 0.3]
['NEUTROPHILS ABSOLUTE COUNT']
['NEUTROPHILS ABSOLUTE COUNT', 3.18]
['NEUTROPHILS ABSOLUTE COUNT']
['NEUTROPHILS ABSOLUTE COUNT', 3.18]
['LYMPHOCYTES ABSOLUTE COUNT']
['LYMPHOCYTES ABSOLUTE COUNT', 2.74]
['MONOCYTES ABSOLUTE COUNT']
['MONOCYTES ABSOLUTE COUNT', 0.15]
['MONOCYTES ABSOLUTE COUNT']
['MONOCYTES ABSOLUTE COUNT', 0.15]
['BASOPHILS ABSOLUTE COUNT']
['BASOPHILS ABSOLUTE COUNT', 0.01]
['BASOPHILS ABSOLUTE COUNT']
['BASOPHILS ABSOLUTE COUNT', 0.01]
['EOSINOPHILS ABSOLUTE COUNT']
['EOSINOPHILS ABSOLUTE COUNT', 0.3]
['EOSINOPHILS ABSOLUTE COUNT']
['EOSINOPHILS ABSOLUTE COUNT', 0.3]
['GRANULOCYTES(IG)']
['GRANULOCYTES(IG)', 0.02]
['TOTAL RBC']
['TOTAL RBC', 6.13]
['NUCLEATED RED BLOOD CELLS']
['NUCLEATED RED BLOOD CELLS', 'CELLS']
['NUCLEATED RED BLOOD CELLS']
['NUCLEATED RED BLOOD CELLS', 'CELLS']
['HEMOGLOBIN']
['HEMOGLOBIN', 18.1]
['HEMATOCRIT(PCV)']
['HEMATOCRIT(PCV)', 50.68]
['MEAN CORPUSCULAR VOLUME(MCV)']
['MEAN CORPUSCULAR VOLUME(MCV)', 100.2]
['MEAN CORPUSCULAR HEMOGLOBIN(MCH)']
['MEAN CORPUSCULAR HEMOGLOBIN(MCH)', 29.5]
['MEAN CORP.HEMO.CONC(MCHC)']
['MEAN CORP.HEMO.CONC(MCHC)', 29.5]
['RED CELL DISTRIBUTION WIDTH SD(RDW-SD)']
['RED CELL DISTRIBUTION WIDTH SD(RDW-SD)', 62.9]
['RED CELL DISTRIBUTION WIDTH (RDW-CV)']
['RED CELL DISTRIBUTION WIDTH (RDW-CV)', 17.6]
['PLATELET DISTRIBUTION WIDTH(PDW)']
['PLATELET DISTRIBUTION WIDTH(PDW)', 11.1]
['MEAN PLATELET VOLUME(MPV)']
['MEAN PLATELET VOLUME(MPV)', 9.4]
['PLATELET COUNT']
['PLATELET COUNT', 222.0]
['PLATELET TO LARGE CELL RATIO(PLCR)']
['PLATELET TO LARGE CELL RATIO(PLCR)', 20.5]
['PLATELETCRIT(PCT)']
['PLATELETCRIT(PCT)', 0.21]
['IRON']
['IRON', 69.1]
['TOTAL IRON BINDING CAPACITY (TIBC)']
['TOTAL IRON BINDING CAPACITY (TIBC)', 348.0]
['TRANSFERRIN SATURATION']
['TRANSFERRIN SATURATION', 19.86]
['ALKALINE PHOSPHATASE 45']
['ALKALINE PHOSPHATASE 45', 129.0]
['BILIRUBIN TOTAL']
['BILIRUBIN TOTAL', 0.35]
['BILIRUBIN -DIRECT 0.3']
['BILIRUBIN -DIRECT 0.3', 0.08]
['BILIRUBIN (INDIRECT)']
['BILIRUBIN (INDIRECT)', 0.27]
['GAMMA GLUTAMYL TRANSFERASE (GGT)']
['GAMMA GLUTAMYL TRANSFERASE (GGT)', 91.1]
['ASPARTATE AMINOTRANSFERASE (SGOT']
['ASPARTATE AMINOTRANSFERASE (SGOT', 22.5]
['ALANINE TRANSAMINASE (SGPT) 45']
['ALANINE TRANSAMINASE (SGPT) 45', 21.4]
['PROTEIN TOTAL']
['PROTEIN TOTAL', 6.6]
['ALBUMIN SERUM']
['ALBUMIN SERUM', 41.0]
['SERUM ALB/GLOBULIN 0.9-2']
['SERUM ALB/GLOBULIN 0.9-2', 1.64]
['SERUM GLOBULIN']
['SERUM GLOBULIN', 2.5]
['TOTAL CHOLESTEROL']
['TOTAL CHOLESTEROL', 220.0]
['HDL CHOLESTEROL DIRECT']
['HDL CHOLESTEROL DIRECT', 36.0]
['LDL CHOLESTEROL DIRECT']
['LDL CHOLESTEROL DIRECT', 167.0]
['TRIGLYCERIDES']
['TRIGLYCERIDES', 188.0]
['TC/ HDL CHOLESTEROL']
['TC/ HDL CHOLESTEROL', 6.1]
['LDL HDL']
['LDL HDL', 4.7]
['VLDL CHOLESTEROL']
['VLDL CHOLESTEROL', 37.6]
['NON-HDL CHOLESTEROL 160']
['NON-HDL CHOLESTEROL 160', 184.1]
['TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES']
['TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES', 'TRIGLYCERIDES']
['TOTAL TRIIODOTHYRONINE (T3)']
['TOTAL TRIIODOTHYRONINE (T3)', 99.0]
['TOTAL THYROXINE (T4)']
['TOTAL THYROXINE (T4)', 6.4]
['THYROID STIMULATING HORMONE (TSH)']
['THYROID STIMULATING HORMONE (TSH)', 3.42]
['BLOOD UREA NITROGEN (BUN)']
['BLOOD UREA NITROGEN (BUN)', 12.26]
['CREATININE SERUM']
['CREATININE SERUM', 0.74]
['BUN SR.CREATININE']
['BUN SR.CREATININE', 16.57]
['CALCIUM']
['CALCIUM', 9.16]
['URIC ACID 4.2']
['URIC ACID 4.2', 3.3]
['EST. GLOMERULAR FILTRATION RATE']
['EST. GLOMERULAR FILTRATION RATE', 117.0]

In [136]:
data

[['H.P.L.C', 8.3],
 ['AVERAGE BLOOD GLUCOSE (ABG)', 192.0],
 ['TOTAL LEUCOCYTES COUNT', 6.4],
 ['NEUTROPHILS', 49.7],
 ['LYMPHOCYTE PERCENTAGE', 42.8],
 ['MONOCYTES', 2.3],
 ['EOSINOPHILS', 4.7],
 ['BASOPHILS', 0.2],
 ['GRANULOCYTE', 0.3],
 ['NEUTROPHILS ABSOLUTE COUNT', 3.18],
 ['NEUTROPHILS ABSOLUTE COUNT', 3.18],
 ['LYMPHOCYTES ABSOLUTE COUNT', 2.74],
 ['MONOCYTES ABSOLUTE COUNT', 0.15],
 ['MONOCYTES ABSOLUTE COUNT', 0.15],
 ['BASOPHILS ABSOLUTE COUNT', 0.01],
 ['BASOPHILS ABSOLUTE COUNT', 0.01],
 ['EOSINOPHILS ABSOLUTE COUNT', 0.3],
 ['EOSINOPHILS ABSOLUTE COUNT', 0.3],
 ['GRANULOCYTES(IG)', 0.02],
 ['TOTAL RBC', 6.13],
 ['NUCLEATED RED BLOOD CELLS', 'CELLS'],
 ['NUCLEATED RED BLOOD CELLS', 'CELLS'],
 ['HEMOGLOBIN', 18.1],
 ['HEMATOCRIT(PCV)', 50.68],
 ['MEAN CORPUSCULAR VOLUME(MCV)', 100.2],
 ['MEAN CORPUSCULAR HEMOGLOBIN(MCH)', 29.5],
 ['MEAN CORP.HEMO.CONC(MCHC)', 29.5],
 ['RED CELL DISTRIBUTION WIDTH SD(RDW-SD)', 62.9],
 ['RED CELL DISTRIBUTION WIDTH (RDW-CV)', 17.6],
 ['PLATELET DISTRIBUTION WIDTH(PDW)', 11.1],
 ['MEAN PLATELET VOLUME(MPV)', 9.4],
 ['PLATELET COUNT', 222.0],
 ['PLATELET TO LARGE CELL RATIO(PLCR)', 20.5],
 ['PLATELETCRIT(PCT)', 0.21],
 ['IRON', 69.1],
 ['TOTAL IRON BINDING CAPACITY (TIBC)', 348.0],
 ['TRANSFERRIN SATURATION', 19.86],
 ['ALKALINE PHOSPHATASE 45', 129.0],
 ['BILIRUBIN TOTAL', 0.35],
 ['BILIRUBIN -DIRECT 0.3', 0.08],
 ['BILIRUBIN (INDIRECT)', 0.27],
 ['GAMMA GLUTAMYL TRANSFERASE (GGT)', 91.1],
 ['ASPARTATE AMINOTRANSFERASE (SGOT', 22.5],
 ['ALANINE TRANSAMINASE (SGPT) 45', 21.4],
 ['PROTEIN TOTAL', 6.6],
 ['ALBUMIN SERUM', 41.0],
 ['SERUM ALB/GLOBULIN 0.9-2', 1.64],
 ['SERUM GLOBULIN', 2.5],
 ['TOTAL CHOLESTEROL', 220.0],
 ['HDL CHOLESTEROL DIRECT', 36.0],
 ['LDL CHOLESTEROL DIRECT', 167.0],
 ['TRIGLYCERIDES', 188.0],
 ['TC/ HDL CHOLESTEROL', 6.1],
 ['LDL HDL', 4.7],
 ['VLDL CHOLESTEROL', 37.6],
 ['NON-HDL CHOLESTEROL 160', 184.1],
 ['TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES', 'TRIGLYCERIDES'],
 ['TOTAL TRIIODOTHYRONINE (T3)', 99.0],
 ['TOTAL THYROXINE (T4)', 6.4],
 ['THYROID STIMULATING HORMONE (TSH)', 3.42],
 ['BLOOD UREA NITROGEN (BUN)', 12.26],
 ['CREATININE SERUM', 0.74],
 ['BUN SR.CREATININE', 16.57],
 ['CALCIUM', 9.16],
 ['URIC ACID 4.2', 3.3],
 ['EST. GLOMERULAR FILTRATION RATE', 117.0]]

In [171]:
columns_name = ['Keywords','Values']

In [181]:
df = pd.DataFrame(data)
df.head()

                             0     1
0                      H.P.L.C   8.3
1  AVERAGE BLOOD GLUCOSE (ABG)   192
2       TOTAL LEUCOCYTES COUNT   6.4
3                  NEUTROPHILS  49.7
4        LYMPHOCYTE PERCENTAGE  42.8

In [182]:
df.columns = ['Keys','Values']

In [188]:
df['Keys'] = df['Keys'].str.replace('\d+', '')
#df['Keys'] = df['Keys'].str.replace('\.','')
#df['Keys'] = df['Keys'].replace({'.':'-'}, regex=True)

In [192]:
df['Keys'] = df['Keys'].str.replace('\.','')
df['Keys'] = df['Keys'].str.replace('\-','')

In [193]:
#df = df.set_index("Keys")

In [194]:
df.head(60)

                                       Keys         Values
0                                      HPLC            8.3
1               AVERAGE BLOOD GLUCOSE (ABG)            192
2                    TOTAL LEUCOCYTES COUNT            6.4
3                               NEUTROPHILS           49.7
4                     LYMPHOCYTE PERCENTAGE           42.8
5                                 MONOCYTES            2.3
6                               EOSINOPHILS            4.7
7                                 BASOPHILS            0.2
8                               GRANULOCYTE            0.3
9                NEUTROPHILS ABSOLUTE COUNT           3.18
10               NEUTROPHILS ABSOLUTE COUNT           3.18
11               LYMPHOCYTES ABSOLUTE COUNT           2.74
12                 MONOCYTES ABSOLUTE COUNT           0.15
13                 MONOCYTES ABSOLUTE COUNT           0.15
14                 BASOPHILS ABSOLUTE COUNT           0.01
15                 BASOPHILS ABSOLUTE COUNT           0.01
16               EOSINOPHILS ABSOLUTE COUNT            0.3
17               EOSINOPHILS ABSOLUTE COUNT            0.3
18                         GRANULOCYTES(IG)           0.02
19                                TOTAL RBC           6.13
20                NUCLEATED RED BLOOD CELLS          CELLS
21                NUCLEATED RED BLOOD CELLS          CELLS
22                               HEMOGLOBIN           18.1
23                          HEMATOCRIT(PCV)          50.68
24             MEAN CORPUSCULAR VOLUME(MCV)          100.2
25         MEAN CORPUSCULAR HEMOGLOBIN(MCH)           29.5
26                  MEAN CORPHEMOCONC(MCHC)           29.5
27    RED CELL DISTRIBUTION WIDTH SD(RDWSD)           62.9
28      RED CELL DISTRIBUTION WIDTH (RDWCV)           17.6
29         PLATELET DISTRIBUTION WIDTH(PDW)           11.1
30                MEAN PLATELET VOLUME(MPV)            9.4
31                           PLATELET COUNT            222
32       PLATELET TO LARGE CELL RATIO(PLCR)           20.5
33                        PLATELETCRIT(PCT)           0.21
34                                     IRON           69.1
35       TOTAL IRON BINDING CAPACITY (TIBC)            348
36                   TRANSFERRIN SATURATION          19.86
37                    ALKALINE PHOSPHATASE             129
38                          BILIRUBIN TOTAL           0.35
39                        BILIRUBIN DIRECT            0.08
40                     BILIRUBIN (INDIRECT)           0.27
41         GAMMA GLUTAMYL TRANSFERASE (GGT)           91.1
42         ASPARTATE AMINOTRANSFERASE (SGOT           22.5
43             ALANINE TRANSAMINASE (SGPT)            21.4
44                            PROTEIN TOTAL            6.6
45                            ALBUMIN SERUM             41
46                      SERUM ALB/GLOBULIN            1.64
47                           SERUM GLOBULIN            2.5
48                        TOTAL CHOLESTEROL            220
49                   HDL CHOLESTEROL DIRECT             36
50                   LDL CHOLESTEROL DIRECT            167
51                            TRIGLYCERIDES            188
52                      TC/ HDL CHOLESTEROL            6.1
53                                  LDL HDL            4.7
54                         VLDL CHOLESTEROL           37.6
55                      NONHDL CHOLESTEROL           184.1
56  TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES  TRIGLYCERIDES
57               TOTAL TRIIODOTHYRONINE (T)             99
58                      TOTAL THYROXINE (T)            6.4
59        THYROID STIMULATING HORMONE (TSH)           3.42

In [164]:
df

                                Values
Keys
H.P.L.C                            8.3
AVERAGE BLOOD GLUCOSE (ABG)        192
TOTAL LEUCOCYTES COUNT             6.4
NEUTROPHILS                       49.7
LYMPHOCYTE PERCENTAGE             42.8
...                                ...
CREATININE SERUM                  0.74
BUN SR.CREATININE                16.57
CALCIUM                           9.16
URIC ACID .                        3.3
EST. GLOMERULAR FILTRATION RATE    117

[66 rows x 1 columns]

In [144]:
#df = df1.transpose()

In [145]:
#df1.drop_duplicates(subset ="Keywords",keep = False, inplace = True)

In [146]:
#df['Keys'] = df['Keys'].str.replace('\d+', '')

In [147]:
#df.columns = ['Keys','Values']

In [148]:
#df = df.set_index("Keys")

In [149]:
df.head(60)

                                                Values
Keys
H.P.L.C                                            8.3
AVERAGE BLOOD GLUCOSE (ABG)                        192
TOTAL LEUCOCYTES COUNT                             6.4
NEUTROPHILS                                       49.7
LYMPHOCYTE PERCENTAGE                             42.8
MONOCYTES                                          2.3
EOSINOPHILS                                        4.7
BASOPHILS                                          0.2
GRANULOCYTE                                        0.3
NEUTROPHILS ABSOLUTE COUNT                        3.18
NEUTROPHILS ABSOLUTE COUNT                        3.18
LYMPHOCYTES ABSOLUTE COUNT                        2.74
MONOCYTES ABSOLUTE COUNT                          0.15
MONOCYTES ABSOLUTE COUNT                          0.15
BASOPHILS ABSOLUTE COUNT                          0.01
BASOPHILS ABSOLUTE COUNT                          0.01
EOSINOPHILS ABSOLUTE COUNT                         0.3
EOSINOPHILS ABSOLUTE COUNT                         0.3
GRANULOCYTES(IG)                                  0.02
TOTAL RBC                                         6.13
NUCLEATED RED BLOOD CELLS                        CELLS
NUCLEATED RED BLOOD CELLS                        CELLS
HEMOGLOBIN                                        18.1
HEMATOCRIT(PCV)                                  50.68
MEAN CORPUSCULAR VOLUME(MCV)                     100.2
MEAN CORPUSCULAR HEMOGLOBIN(MCH)                  29.5
MEAN CORP.HEMO.CONC(MCHC)                         29.5
RED CELL DISTRIBUTION WIDTH SD(RDW-SD)            62.9
RED CELL DISTRIBUTION WIDTH (RDW-CV)              17.6
PLATELET DISTRIBUTION WIDTH(PDW)                  11.1
MEAN PLATELET VOLUME(MPV)                          9.4
PLATELET COUNT                                     222
PLATELET TO LARGE CELL RATIO(PLCR)                20.5
PLATELETCRIT(PCT)                                 0.21
IRON                                              69.1
TOTAL IRON BINDING CAPACITY (TIBC)                 348
TRANSFERRIN SATURATION                           19.86
ALKALINE PHOSPHATASE                               129
BILIRUBIN TOTAL                                   0.35
BILIRUBIN -DIRECT .                               0.08
BILIRUBIN (INDIRECT)                              0.27
GAMMA GLUTAMYL TRANSFERASE (GGT)                  91.1
ASPARTATE AMINOTRANSFERASE (SGOT                  22.5
ALANINE TRANSAMINASE (SGPT)                       21.4
PROTEIN TOTAL                                      6.6
ALBUMIN SERUM                                       41
SERUM ALB/GLOBULIN .-                             1.64
SERUM GLOBULIN                                     2.5
TOTAL CHOLESTEROL                                  220
HDL CHOLESTEROL DIRECT                              36
LDL CHOLESTEROL DIRECT                             167
TRIGLYCERIDES                                      188
TC/ HDL CHOLESTEROL                                6.1
LDL HDL                                            4.7
VLDL CHOLESTEROL                                  37.6
NON-HDL CHOLESTEROL                              184.1
TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES  TRIGLYCERIDES
TOTAL TRIIODOTHYRONINE (T)                          99
TOTAL THYROXINE (T)                                6.4
THYROID STIMULATING HORMONE (TSH)                 3.42

In [73]:
df.to_csv('dataset.csv')

In [74]:
df1 = pd.read_csv('dataset.csv')

In [75]:
df1

                               Keys Values
0                           H.P.L.C    8.3
1       AVERAGE BLOOD GLUCOSE (ABG)  192.0
2            TOTAL LEUCOCYTES COUNT    6.4
3                       NEUTROPHILS   49.7
4             LYMPHOCYTE PERCENTAGE   42.8
..                              ...    ...
61                 CREATININE SERUM   0.74
62              BUN / SR.CREATININE  16.57
63                          CALCIUM   9.16
64                    URIC ACID 4.2    3.3
65  EST. GLOMERULAR FILTRATION RATE  117.0

[66 rows x 2 columns]

In [76]:
df1.columns

Index(['Keys', 'Values'], dtype='object')

In [77]:
df1.drop_duplicates(subset = 'Keys',keep = False, inplace = True)

In [78]:
df1 = df1.dropna(axis=1)

In [79]:
df1.to_json('df1_data.json',orient='values')

In [80]:
df1

                                       Keys         Values
0                                   H.P.L.C            8.3
1               AVERAGE BLOOD GLUCOSE (ABG)          192.0
2                    TOTAL LEUCOCYTES COUNT            6.4
3                               NEUTROPHILS           49.7
4                     LYMPHOCYTE PERCENTAGE           42.8
5                                 MONOCYTES            2.3
6                               EOSINOPHILS            4.7
7                                 BASOPHILS            0.2
8                               GRANULOCYTE            0.3
11               LYMPHOCYTES ABSOLUTE COUNT           2.74
18                         GRANULOCYTES(IG)           0.02
19                                TOTAL RBC           6.13
22                               HEMOGLOBIN           18.1
23                          HEMATOCRIT(PCV)          50.68
24             MEAN CORPUSCULAR VOLUME(MCV)          100.2
25         MEAN CORPUSCULAR HEMOGLOBIN(MCH)           29.5
26                MEAN CORP.HEMO.CONC(MCHC)           29.5
27   RED CELL DISTRIBUTION WIDTH SD(RDW-SD)           62.9
28     RED CELL DISTRIBUTION WIDTH (RDW-CV)           17.6
29         PLATELET DISTRIBUTION WIDTH(PDW)           11.1
30                MEAN PLATELET VOLUME(MPV)            9.4
31                           PLATELET COUNT          222.0
32       PLATELET TO LARGE CELL RATIO(PLCR)           20.5
33                        PLATELETCRIT(PCT)           0.21
34                                     IRON           69.1
35       TOTAL IRON BINDING CAPACITY (TIBC)          348.0
36                   TRANSFERRIN SATURATION          19.86
37                  ALKALINE PHOSPHATASE 45          129.0
38                          BILIRUBIN TOTAL           0.35
39                    BILIRUBIN -DIRECT 0.3           0.08
40                     BILIRUBIN (INDIRECT)           0.27
41         GAMMA GLUTAMYL TRANSFERASE (GGT)           91.1
42         ASPARTATE AMINOTRANSFERASE (SGOT           22.5
43           ALANINE TRANSAMINASE (SGPT) 45           21.4
44                            PROTEIN TOTAL            6.6
45                            ALBUMIN SERUM           41.0
46                 SERUM ALB/GLOBULIN 0.9-2           1.64
47                           SERUM GLOBULIN            2.5
48                        TOTAL CHOLESTEROL          220.0
49                   HDL CHOLESTEROL DIRECT           36.0
50                   LDL CHOLESTEROL DIRECT          167.0
51                            TRIGLYCERIDES          188.0
52                      TC/ HDL CHOLESTEROL            6.1
53                                LDL / HDL            4.7
54                         VLDL CHOLESTEROL           37.6
55                  NON-HDL CHOLESTEROL 160          184.1
56  TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES  TRIGLYCERIDES
57              TOTAL TRIIODOTHYRONINE (T3)           99.0
58                     TOTAL THYROXINE (T4)            6.4
59        THYROID STIMULATING HORMONE (TSH)           3.42
60                BLOOD UREA NITROGEN (BUN)          12.26
61                         CREATININE SERUM           0.74
62                      BUN / SR.CREATININE          16.57
63                                  CALCIUM           9.16
64                            URIC ACID 4.2            3.3
65          EST. GLOMERULAR FILTRATION RATE          117.0

In [81]:
df1 = df1.set_index("Keys")

In [82]:
df1

                                                Values
Keys
H.P.L.C                                            8.3
AVERAGE BLOOD GLUCOSE (ABG)                      192.0
TOTAL LEUCOCYTES COUNT                             6.4
NEUTROPHILS                                       49.7
LYMPHOCYTE PERCENTAGE                             42.8
MONOCYTES                                          2.3
EOSINOPHILS                                        4.7
BASOPHILS                                          0.2
GRANULOCYTE                                        0.3
LYMPHOCYTES ABSOLUTE COUNT                        2.74
GRANULOCYTES(IG)                                  0.02
TOTAL RBC                                         6.13
HEMOGLOBIN                                        18.1
HEMATOCRIT(PCV)                                  50.68
MEAN CORPUSCULAR VOLUME(MCV)                     100.2
MEAN CORPUSCULAR HEMOGLOBIN(MCH)                  29.5
MEAN CORP.HEMO.CONC(MCHC)                         29.5
RED CELL DISTRIBUTION WIDTH SD(RDW-SD)            62.9
RED CELL DISTRIBUTION WIDTH (RDW-CV)              17.6
PLATELET DISTRIBUTION WIDTH(PDW)                  11.1
MEAN PLATELET VOLUME(MPV)                          9.4
PLATELET COUNT                                   222.0
PLATELET TO LARGE CELL RATIO(PLCR)                20.5
PLATELETCRIT(PCT)                                 0.21
IRON                                              69.1
TOTAL IRON BINDING CAPACITY (TIBC)               348.0
TRANSFERRIN SATURATION                           19.86
ALKALINE PHOSPHATASE 45                          129.0
BILIRUBIN TOTAL                                   0.35
BILIRUBIN -DIRECT 0.3                             0.08
BILIRUBIN (INDIRECT)                              0.27
GAMMA GLUTAMYL TRANSFERASE (GGT)                  91.1
ASPARTATE AMINOTRANSFERASE (SGOT                  22.5
ALANINE TRANSAMINASE (SGPT) 45                    21.4
PROTEIN TOTAL                                      6.6
ALBUMIN SERUM                                     41.0
SERUM ALB/GLOBULIN 0.9-2                          1.64
SERUM GLOBULIN                                     2.5
TOTAL CHOLESTEROL                                220.0
HDL CHOLESTEROL DIRECT                            36.0
LDL CHOLESTEROL DIRECT                           167.0
TRIGLYCERIDES                                    188.0
TC/ HDL CHOLESTEROL                                6.1
LDL / HDL                                          4.7
VLDL CHOLESTEROL                                  37.6
NON-HDL CHOLESTEROL 160                          184.1
TOTAL CHOLESTEROL HDL LDL TRIGLYCERIDES  TRIGLYCERIDES
TOTAL TRIIODOTHYRONINE (T3)                       99.0
TOTAL THYROXINE (T4)                               6.4
THYROID STIMULATING HORMONE (TSH)                 3.42
BLOOD UREA NITROGEN (BUN)                        12.26
CREATININE SERUM                                  0.74
BUN / SR.CREATININE                              16.57
CALCIUM                                           9.16
URIC ACID 4.2                                      3.3
EST. GLOMERULAR FILTRATION RATE                  117.0

In [83]:
df1.to_json('nee_data.json',orient='records')

In [34]:
d2 = df1.transpose()

In [35]:
d2

Keys,TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng/d|,TOTAL THYROXINE (T4) C.L.L.A,THYROID STIMULATING HORMONE (TSH) C.LI.A HIU/ml
Values,118.0,12.9,5.14

In [36]:
dfdict =d2.to_dict()

In [37]:
d2.to_json('d2.json',orient='records')

In [38]:
dfdict

{'TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng/d|': {'Values': 118.0},
 'TOTAL THYROXINE (T4) C.L.L.A': {'Values': 12.9},
 'THYROID STIMULATING HORMONE (TSH) C.LI.A HIU/ml': {'Values': 5.14}}

In [39]:
result = d2.to_json(orient="records")

In [40]:
print(result)

[{"TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng\/d|":118.0,"TOTAL THYROXINE (T4) C.L.L.A":12.9,"THYROID STIMULATING HORMONE (TSH) C.LI.A HIU\/ml":5.14}]

In [41]:
d2.to_string(index=False)

' TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng/d|  TOTAL THYROXINE (T4) C.L.L.A  THYROID STIMULATING HORMONE (TSH) C.LI.A HIU/ml\n                                    118.0                          12.9                                             5.14'

In [42]:
# Creating the Series 
sr = pd.Series(dfdict) 
  
# Print the series 
print(sr)

TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng/d|           {'Values': 118.0}
TOTAL THYROXINE (T4) C.L.L.A                        {'Values': 12.9}
THYROID STIMULATING HORMONE (TSH) C.LI.A HIU/ml     {'Values': 5.14}
dtype: object

In [43]:
dic = dict(df1)

In [44]:
sr = pd.Series(dic)

In [45]:
sr

Values    Keys
TOTAL TRIIODOTHYRONINE (T3) C.LI.A ng/d| ...
dtype: object